/* Curated sights & photo stops along (and near) the GAP + C&O route.
 * stars: 3 = don't miss, 2 = worth the stop, 1 = only if you're fresh.
 * snap: true = trailside feature; tools/snap_sights.py moves it exactly onto
 * the route line. snap: false = real off-trail location (short detour).
 * desc = English, desc_es = Spanish (i18n).
 */
const SIGHTS = [
 {"day": 1, "stars": 2, "snap": false, "lat": 40.4396, "lng": -80.0184, "name": "Duquesne Incline", "desc": "1877 cable car up Mt. Washington — the classic Pittsburgh skyline photo. Across the bridge from the start; do it the evening before.", "desc_es": "Funicular de 1877 que sube al Mt. Washington — la clásica foto del horizonte de Pittsburgh. Cruzando el puente desde la salida; háganlo la tarde anterior."},
 {"day": 1, "stars": 1, "snap": true, "lat": 40.42732, "lng": -79.96251, "name": "Hot Metal Bridge", "desc": "You ride across this former steel-mill bridge that once carried molten iron between furnaces.", "desc_es": "Cruzarán este antiguo puente de la acerera que transportaba hierro fundido entre hornos."},
 {"day": 1, "stars": 1, "snap": true, "lat": 40.41007, "lng": -79.89667, "name": "The Pump House, Homestead", "desc": "Site of the 1892 Battle of Homestead steel strike. Quick trailside history stop.", "desc_es": "Sitio de la huelga acerera de Homestead de 1892. Parada histórica rápida junto al sendero."},
 {"day": 1, "stars": 1, "snap": true, "lat": 40.27491, "lng": -79.79822, "name": "Dravo Cemetery", "desc": "Pioneer cemetery from 1812 right beside the trail. Shady bench break.", "desc_es": "Cementerio pionero de 1812 junto al sendero. Descanso con sombra y bancas."},
 {"day": 1, "stars": 1, "snap": true, "lat": 40.18916, "lng": -79.76003, "name": "Cedar Creek Park", "desc": "Riverside park with a small gorge. Restrooms and water.", "desc_es": "Parque ribereño con una pequeña cañada. Baños y agua."},
 {"day": 2, "stars": 3, "snap": false, "lat": 39.8653, "lng": -79.5006, "name": "Cucumber Falls", "desc": "30-ft bridal-veil waterfall, a 5-minute walk off the trail in Ohiopyle. Top photo stop of the whole trip.", "desc_es": "Cascada velo de novia de 9 m, a 5 minutos a pie del sendero en Ohiopyle. La mejor foto de todo el viaje."},
 {"day": 2, "stars": 3, "snap": false, "lat": 39.8674, "lng": -79.4945, "name": "Ohiopyle Falls", "desc": "The big Youghiogheny falls with viewing decks right in town. Pair with ice cream.", "desc_es": "Las grandes cascadas del Youghiogheny con miradores en el mismo pueblo. Combínenlo con un helado."},
 {"day": 2, "stars": 2, "snap": false, "lat": 39.8713, "lng": -79.4986, "name": "Ferncliff Peninsula", "desc": "Natural-area loop inside a river bend — rare plants and river views.", "desc_es": "Circuito natural dentro de una curva del río — plantas raras y vistas al agua."},
 {"day": 2, "stars": 2, "snap": false, "lat": 39.9064, "lng": -79.4677, "name": "Fallingwater", "desc": "Frank Lloyd Wright's world-famous house over a waterfall. ~4 mi off trail and needs tickets + 2-3 hours — only with time to spare.", "desc_es": "La casa sobre la cascada de Frank Lloyd Wright, famosa en el mundo. ~6 km fuera del sendero, requiere boletos y 2-3 horas — solo si sobra tiempo."},
 {"day": 2, "stars": 3, "snap": true, "lat": 39.83357, "lng": -79.04455, "name": "Salisbury Viaduct", "desc": "1,908-ft railroad viaduct you ride straight across, high above the Casselman valley. Sweeping views — don't rush it.", "desc_es": "Viaducto ferroviario de 580 m que cruzarán pedaleando, en lo alto del valle del Casselman. Vistas panorámicas — no lo crucen de prisa."},
 {"day": 3, "stars": 2, "snap": true, "lat": 39.72181, "lng": -78.90485, "name": "Mason–Dixon Line", "desc": "Cross from Pennsylvania into Maryland at the surveyed 1767 line — marker on the trail.", "desc_es": "Cruce de Pensilvania a Maryland en la línea trazada en 1767 — hay un monumento en el sendero."},
 {"day": 3, "stars": 1, "snap": true, "lat": 39.67778, "lng": -78.80687, "name": "Helmstetter's Curve", "desc": "Famous horseshoe curve of the scenic railroad — photo spot if a steam train happens by.", "desc_es": "Famosa curva de herradura del tren escénico — buena foto si pasa una locomotora de vapor."},
 {"day": 3, "stars": 2, "snap": true, "lat": 39.6468, "lng": -78.76333, "name": "Canal Place — C&O Mile 0", "desc": "Where the GAP ends and the C&O Canal begins. Obligatory marker photo in Cumberland.", "desc_es": "Donde termina el GAP y empieza el canal C&O. Foto obligada con el marcador en Cumberland."},
 {"day": 3, "stars": 2, "snap": true, "lat": 39.67402, "lng": -78.23355, "name": "Round Top Cement Mill", "desc": "Civil-War-era cement kiln ruins built into the cliff just west of Hancock.", "desc_es": "Ruinas de hornos de cemento de la Guerra Civil, empotradas en el acantilado al oeste de Hancock."},
 {"day": 4, "stars": 2, "snap": true, "lat": 39.61408, "lng": -77.92565, "name": "Dam No. 5", "desc": "Potomac dam Stonewall Jackson tried to blow up in 1861. Dramatic water over the rocks.", "desc_es": "Presa del Potomac que Stonewall Jackson intentó volar en 1861. Agua impresionante sobre las rocas."},
 {"day": 4, "stars": 1, "snap": true, "lat": 39.49828, "lng": -77.83888, "name": "Dam No. 4", "desc": "Start of the Big Slackwater stretch where the towpath hugs the river on a concrete shelf.", "desc_es": "Inicio del tramo Big Slackwater, donde el sendero abraza el río sobre una plataforma de concreto."},
 {"day": 4, "stars": 3, "snap": false, "lat": 39.4747, "lng": -77.7445, "name": "Antietam Battlefield", "desc": "Bloodiest single day of the Civil War (1862). ~4 mi off trail from Sharpsburg — a real detour, but historic ground.", "desc_es": "El día más sangriento de la Guerra Civil (1862). ~6 km fuera del sendero desde Sharpsburg — un desvío de verdad, pero es terreno histórico."},
 {"day": 4, "stars": 1, "snap": true, "lat": 39.46069, "lng": -77.77617, "name": "Antietam Aqueduct", "desc": "Stone canal aqueduct over Antietam Creek, right on the towpath.", "desc_es": "Acueducto de piedra del canal sobre el arroyo Antietam, sobre el mismo sendero."},
 {"day": 5, "stars": 3, "snap": false, "lat": 39.3232, "lng": -77.7299, "name": "Harpers Ferry Lower Town", "desc": "John Brown's Fort, The Point where two rivers meet, cobbled streets. You sleep here — explore in the evening.", "desc_es": "El fuerte de John Brown, The Point donde se unen dos ríos, calles empedradas. Aquí duermen — explórenlo por la tarde."},
 {"day": 5, "stars": 3, "snap": true, "lat": 39.2229, "lng": -77.4515, "name": "Monocacy Aqueduct", "desc": "The grandest C&O aqueduct — seven granite arches, 516 ft. Best photo angle from the downstream side.", "desc_es": "El acueducto más grandioso del C&O — siete arcos de granito, 157 m. La mejor foto es desde el lado río abajo."},
 {"day": 5, "stars": 2, "snap": true, "lat": 39.06856, "lng": -77.33707, "name": "Riley's Lock & Seneca Aqueduct", "desc": "Red sandstone aqueduct and lockhouse in one — quarried right next door.", "desc_es": "Acueducto y casa de esclusa de arenisca roja en una sola estructura — la piedra se extraía aquí mismo."},
 {"day": 5, "stars": 3, "snap": false, "lat": 38.9941, "lng": -77.2536, "name": "Great Falls Overlook (Olmsted Island)", "desc": "THE falls near Washington — boardwalk to a mid-river overlook of the 60-ft cascades. 10-minute walk, do not skip.", "desc_es": "LAS cascadas cerca de Washington — sendero de madera a un mirador en medio del río frente a caídas de 18 m. Caminata de 10 minutos, no se la salten."},
 {"day": 5, "stars": 2, "snap": true, "lat": 38.98968, "lng": -77.24416, "name": "Billy Goat Trail", "desc": "Famous rock-scramble loop over Mather Gorge. Only the overlook section if legs are tired.", "desc_es": "Famoso circuito de trepar rocas sobre la garganta Mather. Solo la sección del mirador si las piernas ya no dan."},
 {"day": 5, "stars": 1, "snap": true, "lat": 38.91885, "lng": -77.10128, "name": "Fletcher's Boathouse", "desc": "Historic boathouse — snacks, drinks, and a last shady break before Georgetown.", "desc_es": "Histórico embarcadero — botanas, bebidas y un último descanso con sombra antes de Georgetown."},
 {"day": 5, "stars": 3, "snap": false, "lat": 38.8893, "lng": -77.0502, "name": "Lincoln Memorial & the Mall", "desc": "One more mile past the finish: roll to the Lincoln Memorial for the victory photo with the Monument behind you.", "desc_es": "Un kilómetro y medio más allá de la meta: pedaleen al Monumento a Lincoln para la foto de la victoria con el obelisco de fondo."}
];
