/* Auto-generated by tools/build_stops.py from OpenStreetMap data.
 * Support-vehicle meet points: spots every ~10 mi where a public road or
 * parking area touches the GAP / C&O trail. Do not edit by hand. */
const VEHICLE_STOPS = [
 {
  "day": 1,
  "tripMile": 9.2,
  "dayMile": 9.2,
  "lat": 40.41325,
  "lng": -79.89753,
  "name": "Pump House Trail Access",
  "kind": "parking"
 },
 {
  "day": 1,
  "tripMile": 20.3,
  "dayMile": 20.3,
  "lat": 40.31068,
  "lng": -79.82844,
  "name": "Boston Trail Access",
  "kind": "parking"
 },
 {
  "day": 1,
  "tripMile": 30.6,
  "dayMile": 30.6,
  "lat": 40.24191,
  "lng": -79.80613,
  "name": "Sutersville Trail Access",
  "kind": "parking"
 },
 {
  "day": 1,
  "tripMile": 40.4,
  "dayMile": 40.4,
  "lat": 40.15788,
  "lng": -79.74623,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 1,
  "tripMile": 46.6,
  "dayMile": 46.6,
  "lat": 40.08878,
  "lng": -79.7295,
  "name": "Trail Parkiing",
  "kind": "parking"
 },
 {
  "day": 1,
  "tripMile": 56.4,
  "dayMile": 56.4,
  "lat": 40.04334,
  "lng": -79.62375,
  "name": "Adelaide Road",
  "kind": "road"
 },
 {
  "day": 2,
  "tripMile": 70.6,
  "dayMile": 10.7,
  "lat": 39.92646,
  "lng": -79.48819,
  "name": "Off-Season Parking",
  "kind": "parking"
 },
 {
  "day": 2,
  "tripMile": 76.7,
  "dayMile": 16.7,
  "lat": 39.86983,
  "lng": -79.49088,
  "name": "Ohiopyle GAP Trail Access",
  "kind": "parking"
 },
 {
  "day": 2,
  "tripMile": 86.7,
  "dayMile": 26.8,
  "lat": 39.81049,
  "lng": -79.36564,
  "name": "Ram Cat Road",
  "kind": "road"
 },
 {
  "day": 2,
  "tripMile": 94.2,
  "dayMile": 34.3,
  "lat": 39.82604,
  "lng": -79.2762,
  "name": "Sechler Road",
  "kind": "road"
 },
 {
  "day": 2,
  "tripMile": 105.9,
  "dayMile": 45.9,
  "lat": 39.91086,
  "lng": -79.16163,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 2,
  "tripMile": 116.2,
  "dayMile": 56.3,
  "lat": 39.8322,
  "lng": -79.04214,
  "name": "Mason Dixon Highway",
  "kind": "road"
 },
 {
  "day": 3,
  "tripMile": 127.7,
  "dayMile": 9.8,
  "lat": 39.74097,
  "lng": -78.89351,
  "name": "Road crossing",
  "kind": "road"
 },
 {
  "day": 3,
  "tripMile": 137.3,
  "dayMile": 19.5,
  "lat": 39.68131,
  "lng": -78.88206,
  "name": "Trimble Road Northwest",
  "kind": "road"
 },
 {
  "day": 3,
  "tripMile": 147.4,
  "dayMile": 29.5,
  "lat": 39.67232,
  "lng": -78.79301,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 3,
  "tripMile": 158.8,
  "dayMile": 41.0,
  "lat": 39.58708,
  "lng": -78.74086,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 3,
  "tripMile": 167.8,
  "dayMile": 49.9,
  "lat": 39.5398,
  "lng": -78.6127,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 3,
  "tripMile": 178.2,
  "dayMile": 60.4,
  "lat": 39.54409,
  "lng": -78.4616,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 3,
  "tripMile": 186.7,
  "dayMile": 68.9,
  "lat": 39.59822,
  "lng": -78.41814,
  "name": "Road crossing",
  "kind": "road"
 },
 {
  "day": 3,
  "tripMile": 198.4,
  "dayMile": 80.6,
  "lat": 39.63578,
  "lng": -78.32319,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 3,
  "tripMile": 208.6,
  "dayMile": 90.7,
  "lat": 39.68351,
  "lng": -78.19884,
  "name": "Berm Road",
  "kind": "road"
 },
 {
  "day": 4,
  "tripMile": 219.7,
  "dayMile": 9.5,
  "lat": 39.63269,
  "lng": -78.02931,
  "name": "Ernstville Road",
  "kind": "road"
 },
 {
  "day": 4,
  "tripMile": 227.7,
  "dayMile": 17.5,
  "lat": 39.60724,
  "lng": -77.9217,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 4,
  "tripMile": 235.1,
  "dayMile": 25.0,
  "lat": 39.59503,
  "lng": -77.82543,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 4,
  "tripMile": 246.4,
  "dayMile": 36.2,
  "lat": 39.53015,
  "lng": -77.82426,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 4,
  "tripMile": 257.7,
  "dayMile": 47.5,
  "lat": 39.46446,
  "lng": -77.77674,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 4,
  "tripMile": 267.5,
  "dayMile": 57.4,
  "lat": 39.3852,
  "lng": -77.73519,
  "name": "Mountain Lock Recreation Area Parking",
  "kind": "parking"
 },
 {
  "day": 5,
  "tripMile": 283.7,
  "dayMile": 10.4,
  "lat": 39.30624,
  "lng": -77.55834,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 5,
  "tripMile": 294.8,
  "dayMile": 21.5,
  "lat": 39.19504,
  "lng": -77.46994,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 5,
  "tripMile": 303.8,
  "dayMile": 30.5,
  "lat": 39.10357,
  "lng": -77.47243,
  "name": "Parking area",
  "kind": "parking"
 },
 {
  "day": 5,
  "tripMile": 314.7,
  "dayMile": 41.4,
  "lat": 39.05616,
  "lng": -77.2934,
  "name": "Boat Ramp Parking Lot",
  "kind": "parking"
 },
 {
  "day": 5,
  "tripMile": 324.7,
  "dayMile": 51.4,
  "lat": 38.97095,
  "lng": -77.19005,
  "name": "Parking area",
  "kind": "parking"
 }
];
